language: java

jdk:
  - oraclejdk8

os:
  - linux

cache:
  directories:
  - .autoconf
  - $HOME/.m2
<<<<<<< HEAD:object-mapper-gson/.travis.yml
=======

# blocklist
branches:
  except:
  - apache5
>>>>>>> upgrade unirest to 5:.travis.yml
